"""
EasyMocap Integration Adapter for Signify 3D SLR.

Ingests multi-camera 3D MANO hand mesh parameters and 3D metric keypoints (X, Y, Z in mm)
generated by EasyMocap (Zhejiang University 3D Vision Group) and projects them into feature space
for PyTorch CSLR BiLSTM CTC Sequence Classification without zero-padding.
"""

import os
import json
import numpy as np
import torch
import torch.nn as nn
from typing import Dict, Any, List, Optional

import sys
sys.path.append(os.path.join(os.path.dirname(__file__), "..", "models"))
from cslr_model import CSLR_BiLSTM_CTC


class EasyMocapAdapter:
    """
    Adapter for processing EasyMocap 3D Keypoint & MANO Mesh Outputs.
    Maps 123-dim 3D mcap vectors into feature manifold via a linear projection layer.
    """

    def __init__(self, weights_path: Optional[str] = "weights/cslr_bilstm.pth"):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model = CSLR_BiLSTM_CTC(input_dim=225, num_glosses=39).to(self.device)
        
        # 123-dim (63 keypoints + 60 bone vectors) -> 225-dim manifold projection
        self.mocap_projection = nn.Linear(123, 225).to(self.device)
        nn.init.orthogonal_(self.mocap_projection.weight)

        self.idx_to_gloss = {i: f"GLOSS_{i}" for i in range(39)}
        self.idx_to_gloss[0] = "<BLANK>"

        if weights_path and os.path.exists(weights_path):
            try:
                self.model.load_state_dict(torch.load(weights_path, map_location=self.device))
                print(f"✅ Loaded CSLR Model weights from {weights_path}")
            except Exception as e:
                print(f"Notice: CSLR model initialized with default architecture ({e})")
        self.model.eval()

    def parse_easymocap_frame(self, easymocap_json_data: Dict[str, Any]) -> Optional[np.ndarray]:
        """
        Parses a single EasyMocap 3D output frame into a 123-dim normalized feature vector:
        - 63 normalized 3D keypoint coordinates (21 x 3)
        - 60 3D bone direction vectors (20 x 3)
        """
        if "people" not in easymocap_json_data or len(easymocap_json_data["people"]) == 0:
            return None

        person = easymocap_json_data["people"][0]
        
        if "hand_right_3d" in person:
            pts3d = np.array(person["hand_right_3d"], dtype=np.float32).reshape(-1, 3)
        elif "pose3d" in person:
            pts3d = np.array(person["pose3d"], dtype=np.float32).reshape(-1, 3)[:21]
        else:
            return None

        if pts3d.shape[0] < 21:
            return None

        wrist = pts3d[0]
        centered = pts3d[:21] - wrist
        scale = np.linalg.norm(centered[9]) + 1e-6
        norm_pts = (centered / scale).flatten()

        bone_pairs = [
            (0,1),(1,2),(2,3),(3,4), (0,5),(5,6),(6,7),(7,8),
            (0,9),(9,10),(10,11),(11,12), (0,13),(13,14),(14,15),(15,16),
            (0,17),(17,18),(18,19),(19,20)
        ]
        bone_vecs = []
        for s, e in bone_pairs:
            v = pts3d[e] - pts3d[s]
            bone_vecs.append(v / (np.linalg.norm(v) + 1e-6))
        norm_bones = np.array(bone_vecs, dtype=np.float32).flatten()

        features = np.concatenate([norm_pts, norm_bones])
        return features

    def predict_easymocap_sequence(self, easymocap_frames: List[Dict[str, Any]]) -> Dict[str, Any]:
        feat_list = []
        for f in easymocap_frames:
            feat = self.parse_easymocap_frame(f)
            if feat is not None:
                feat_list.append(feat)

        if len(feat_list) < 5:
            return {"status": "error", "message": "Sequence too short for CTC recognition"}

        feats_np = np.array(feat_list, dtype=np.float32)  # [Time, 123]
        feats_tensor = torch.tensor(feats_np, dtype=torch.float32).unsqueeze(0).to(self.device)  # [1, Time, 123]

        with torch.no_grad():
            # Project 123-dim mocap features into 225-dim model space
            projected_seq = self.mocap_projection(feats_tensor)  # [1, Time, 225]
            logits = self.model(projected_seq)
            decoded_ids = self.model.decode_greedy(logits)[0]
            decoded_glosses = [self.idx_to_gloss.get(i, f"GLOSS_{i}") for i in decoded_ids]

        return {
            "status": "success",
            "frame_count": len(feat_list),
            "decoded_ids": decoded_ids,
            "sentence": " ".join(decoded_glosses)
        }


if __name__ == "__main__":
    adapter = EasyMocapAdapter()
    dummy_frame = {
        "people": [{
            "pose3d": (np.random.randn(21, 3) * 0.1).tolist()
        }]
    }
    feats = adapter.parse_easymocap_frame(dummy_frame)
    print("✅ Parsed EasyMocap Frame Feature Vector Shape:", feats.shape)
